### ISSUE TITLE
io.cettia.HeartbeatFailedException: null

### ISSUE THREAD

**Issue by zero1zero** [cettia/cettia-java-server#13]
```
io.cettia.HeartbeatFailedException: null
	at io.cettia.DefaultServer$DefaultServerSocket$6.run(DefaultServer.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Unsure what this means but it would appear that `actionsMap.get("error")` is null when it shouldn't be.  Either a check for null or it is being called in the incorrect state.

**Comment by flowersinthesand** [comment]
If actionsMap.get("error") were null, `java.lang.NullPointerException` would have been thrown instead of `io.cettia.HeartbeatFailedException`.

This exception is thrown when heartbeat operations fails. For the details of heartbeat, see http://cettia.io/projects/cettia-java-server/1.0.0-Beta1/reference/#heartbeat

FYI, to reproduce this situation, add an `error` event handler like `socket.onerror((Throwable error) -> error.printStackTrace());` on server, open a socket on client and kill the client process. Then after a few seconds, you should see the above stack trace on server console.

**Comment by zero1zero** [comment]
Ugh, yup. Completely read the exception wrong.   

Is the heartbeat failed exception actually exceptional? Seems like it would happen in the due course of operatiohn.

**Comment by flowersinthesand** [comment]
The heartbeat failed exception is exceptional because it can happen when network failure occurs or client application crashes for some reason.

If there were some errors on connection, `error` event is fired and then `close` event usually follows it. Here, `error` event usually gives you the reason why the connection closed.

**Comment by zero1zero** [comment]
Understood! Makes sense.  Sounds like the answer here is to log with the error exception handler. Thanks!
